import type { Metadata } from "next";
import "./globals.css";
import { Old_Standard_TT, Jost, Caveat } from "next/font/google";

import Footer from "./components/Footer";
import Header from "./components/Header";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const oldStandard = Old_Standard_TT({
    subsets: ["latin"],
    weight: ["400", "700"],
    variable: "--font-old-standard",
});
const jost = Jost({
    subsets: ["latin"],
    weight: ["400", "500", "700"],
    variable: "--font-jost",
    display: "swap",
});

const caveat = Caveat({
    subsets: ["latin"],
    weight: ["700"],
    variable: "--font-caveat",
    display: "swap",
});
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`h-full ${oldStandard.variable} ${jost.variable} ${caveat.variable}`}
        >
            <body className="min-h-screen flex flex-col">
                <Header />
                <main className="flex-1">{children}</main>
                <Footer />
            </body>
        </html>
    );
}
